version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cookiecutter
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - hvalfangstnettverket

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    networks:
      - hvalfangstnettverket

volumes:
  postgres_data:
  redis:
  redis-config:

networks:
  hvalfangstnettverket:
    driver: bridge
