apiVersion: apps/v1
kind: Deployment
metadata:
  name: hvalbanken-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
        - name:  hvalbanken-api
          image: hvalbanken-api:666
          ports:
            - containerPort: 8081
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: database-url
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PORT
              value: "6379"
        - name: redis-master
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: system
  ports:
    - name: api
      port: 8081
      targetPort: 8081
    - name: redis-master
      port: 6379
      targetPort: 6379
  type: LoadBalancer