apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
        - name: db
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: admin
          ports:
            - containerPort: 5432
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: system
  ports:
    - name: db
      port: 5432
      targetPort: 5432
  type: LoadBalancer