apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    worker_processes auto;
    events {
      worker_connections 1024;
    }
    http {
      upstream entrypoint {
        server entrypoint:8081;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://entrypoint;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }