apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-model.config
data:
  nginx.conf: |-
    worker_processes auto;
    events {
      worker_connections 1024;
    }
    http {
      upstream api {
        # Routes requests to k8s service with name 'api' at port 8081
        server api:8081;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://api;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }