apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  database-url: MTAuMTAxLjI0My4xMDQ6NTQzMi9wb3N0Z3Jlcz91c2VyPXBvc3RncmVzJnBhc3N3b3JkPWFkbWlu
  username: ZXJuc3Q=
  password: aGlsbw==